---
- name: Install vim from package repository
  apt:
    name: [vim, exuberant-ctags, ack-grep]
    state: latest
  become: yes

# Download settings from own repository
- name: Download vim folder
  git:
    repo=https://github.com/tixif-ni/dev-vim.git
    dest=~/.vim
    force=yes

- name: Create symlink to vimrc
  file: src=~/.vim/.vimrc dest=~/.vimrc state=link

- name: Create autoload folder
  file: path=~/.vim/autoload state=directory mode=0755

- name: Setup package manager
  get_url:
    url=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest=~/.vim/autoload/plug.vim

- name: Copy ackrc to home
  copy: src=ackrc dest=~/.ackrc 
